version: '3'

services:
  mysql:
    build: ./mysql
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
    volumes:
      - "./mysql/script/init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
    restart: always
    
  web:
    build: ./apache
    container_name: docker-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/www:/var/www/html
    links:
      - mysql